import { 
  FlaskConical, 
  DropletOff, 
  Droplet, 
  Sparkles, 
  Box, 
  Eraser, 
  Archive, 
  CloudOff, 
  Sun, 
  CircleSlash, 
  GlassWater, 
  BoxSelect, 
  Hand, 
  Moon, 
  Heart, 
  Hammer, 
  ShieldAlert,
  Rocket, 
  Gift, 
  Shapes, 
  Bell, 
  Coins, 
  Feather, 
  Sparkle, 
  Gem, 
  Crown, 
  Diamond, 
  Baby, 
  PartyPopper, 
  Handshake,HeartHandshake
} from 'lucide-react';

export const AppIconMap: Record<string, React.ElementType> = {
  "Heart": Heart,
  "Handshake": Handshake,
  "HeartHandshake":HeartHandshake,
  "Gift": Gift,
  "Shapes": Shapes,
  "Bell": Bell,
  "Coins": Coins,
  "Feather": Feather,
  "Sparkle": Sparkle,
  "Gem": Gem,
  "Crown": Crown,
  "Diamond": Diamond,
  "Baby": Baby,
  "PartyPopper": PartyPopper,  
  "Rocket": Rocket,
  "FlaskConical": FlaskConical,
  "DropletOff": DropletOff,
  "Droplet": Droplet,
  "Sparkles": Sparkles,
  "Box": Box,
  "Eraser": Eraser,
  "Archive": Archive,
  "CloudOff": CloudOff,
  "SunOff": Sun,
  "CircleBackslash": CircleSlash,
  "GlassWater": GlassWater,
  "BoxSelect": BoxSelect,
  "Hand": Hand,
  "Moon": Moon,
  "Hammer": Hammer,
  "ShieldAlert": ShieldAlert,
};