import { 
  FlaskConical, 
  DropletOff, 
  Droplet, 
  Sparkles, 
  Box, 
  Eraser, 
  Archive, 
  CloudOff, 
  Sun, 
  CircleSlash, 
  GlassWater, 
  BoxSelect, 
  Hand, 
  Moon, 
  Heart, 
  Hammer, 
  ShieldAlert,
  Rocket // Included as per your example
} from 'lucide-react';

export const AppIconMap: Record<string, React.ElementType> = {
  "Rocket": Rocket,
  "FlaskConical": FlaskConical,
  "DropletOff": DropletOff,
  "Droplet": Droplet,
  "Sparkles": Sparkles,
  "Box": Box,
  "Eraser": Eraser,
  "Archive": Archive,
  "CloudOff": CloudOff,
  "SunOff": Sun,
  "CircleBackslash": CircleSlash,
  "GlassWater": GlassWater,
  "BoxSelect": BoxSelect,
  "Hand": Hand,
  "Moon": Moon,
  "Heart": Heart,
  "Hammer": Hammer,
  "ShieldAlert": ShieldAlert,
};